"""Update illustrations table for multi-AI provider support

Revision ID: ffed9410466b
Revises: f4328cefaa49
Create Date: 2025-09-27 21:39:35.205840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffed9410466b'
down_revision = 'f4328cefaa49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('illustrations', sa.Column('generation_prompt', sa.Text(), nullable=False))
    op.add_column('illustrations', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('illustrations', sa.Column('model_name', sa.String(length=50), nullable=True))
    op.add_column('illustrations', sa.Column('cache_key', sa.String(length=64), nullable=True))
    op.add_column('illustrations', sa.Column('safety_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_illustrations_cache_key'), 'illustrations', ['cache_key'], unique=False)
    op.drop_column('illustrations', 'prompt')
    op.drop_column('illustrations', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('illustrations', sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('illustrations', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_illustrations_cache_key'), table_name='illustrations')
    op.drop_column('illustrations', 'safety_info')
    op.drop_column('illustrations', 'cache_key')
    op.drop_column('illustrations', 'model_name')
    op.drop_column('illustrations', 'provider')
    op.drop_column('illustrations', 'generation_prompt')
    # ### end Alembic commands ###
